cat > docker-compose.prod.yml <<'EOF'
version: '3.8'
services:
  backend:
    image: YOUR_DOCKERHUB_USERNAME/backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    image: YOUR_DOCKERHUB_USERNAME/frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    restart: unless-stopped
EOF
