name: CI/CD Fullstack App → EC2

on:
  push:
    branches: [ main ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build backend image
        run: docker build -f Dockerfile.backend -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .

      - name: Build frontend image
        run: docker build -f Dockerfile.frontend -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .

      - name: Push images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            echo "Checking user and Docker version"
            whoami
            sudo docker --version

            echo "Stopping old containers if any..."
            sudo docker stop frontend backend || true
            sudo docker rm frontend backend || true

            echo "Pulling latest images..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest

            echo "Starting backend..."
            sudo docker run -d -p 5000:5000 --name backend ${{ secrets.DOCKER_USERNAME }}/backend:latest

            echo "Starting frontend..."
            sudo docker run -d -p 80:80 --name frontend ${{ secrets.DOCKER_USERNAME }}/frontend:latest

            echo "Listing running containers:"
            sudo docker ps

